### ISSUE TITLE
Librosa API changed

### ISSUE THREAD

**Issue by beantowel** [keums/MelodyExtraction_MCDNN#5]
in librosa [changelog](https://github.com/librosa/librosa/blob/d4dd6e01c00918518bbd32f8308957c745d69b00/docs/changelog.rst):

> `#627`_ The following functions and features have been removed:
> - `real=` parameter in `cqt`
> - `core.logamplitude` (replaced by `amplitude_to_db`)    **<--- used in your code**
> - `beat.estimate_tempo` (replaced by `beat.tempo`)
> - `n_fft=` parameter to `feature.rmse`
> - `ref_power=` parameter to `power_to_db`

**Comment by BunnyTeng** [comment]
pip install librosa=0.5.0
